# Generated by Django 4.0.6 on 2022-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
