# Generated by Django 4.0.6 on 2022-10-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(),
        ),
    ]
